spring.application.name=Api Dynamic Cards

spring.datasource.url=jdbc:postgresql://192.168.3.150:5432/db_dynamic_cards?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.name=app_card
spring.datasource.password=123

spring.datasource.hikari.username=app_card
spring.datasource.hikari.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true